### PR TITLE
UX improved & fixes added

### LINKED ISSUE #16: Improve UX
Based on my interactions with Linux applications, current GUI UX doesn't feel right.
Here is the list of what I would expect from it. You may disagree with me, so please respond with your expectations.

- [x] Exit dexpo after desktop change event. (Why would I need dexpo running after I have moved to another desktop)
- [x] Display preselection around current _NET_WM_DESKTOP on startup
- [x] Draw border around all desktops
- [x] Border size should not obstruct padding size

And add these options to the config file

### PR DESCRIPTION
**Pull request by TheHussky**
1)Requested UX changes done
2)Requested comments added
3)Minor fixes added

### CODE REVIEW

File: src/dexpo.cpp [hunk 1]
```diff
@@ -77,27 +76,37 @@ main ()
         case XCB_EXPOSE:
           {
             w.draw_gui ();
-            // w.draw_border (0, dexpo_hlcolor);
+            for (int i = 0; int (i < w.desktops.size ()); i++)
+              {
+                w.draw_border (i, dexpo_desktop_color);
+              }
```
Comment (mmskv) [inline src/dexpo.cpp]: lmao why would you declare `i` as an `int` and then explicitly convert it to compare to `size_t` both in `draw_border` and in `int (i < w.desktops.size ()`

Declaring `i` as `size_t` would solve both these issues
though I would change all `size_t` to `uint`

File: src/dexpo.cpp [hunk 2]
```diff
@@ -77,27 +76,37 @@ main ()
...
+            w.desktop_sel = get_property_value (
+                window::c_, window::screen_->root, "_NET_CURRENT_DESKTOP")[0];
```
Comment (mmskv) [inline src/dexpo.cpp]: bro there is a function `get_current_desktop` in `xcb_utils.cpp`

File: src/dexpo.cpp [hunk 3]
```diff
@@ -77,27 +76,37 @@ main ()
...
+            /// Left arrow or up arrow
             bool prev = kp->detail == 113 || kp->detail == 111;
             bool entr = kp->detail == 36; /// Enter
             bool esc = kp->detail == 9;   /// Escape
 
             w.clear_preselection ();
-            if (next) // TODO(mangalinor) Document code
+            if (next)
+              // Pressing right arrow or down arrow
+              // Preselects next desktop
```
Comment (mmskv) [inline src/dexpo.cpp]: That's too explicit, will change it myself

File: src/dexpo.cpp [hunk 4]
```diff
@@ -106,6 +115,14 @@ main ()
...
                 ewmh_change_desktop (window::c_, window::screen_,
                                      w.desktop_sel);
+                // Next line fixes bug that appears while switching to active
+                // desktop
+                if (w.desktop_sel
+                    == get_property_value (window::c_, window::screen_->root,
+                                           "_NET_CURRENT_DESKTOP")[0])
+                  {
+                    return 0;
+                  };
```
Comment (mmskv) [inline src/dexpo.cpp]: ewmh_change_desktop should not run if `w.desktop_sel == get_current_desktop`

What bug does this ifx?

File: src/dexpo.cpp [hunk 5]
```diff
@@ -127,37 +144,25 @@ main ()
...
+              {
+                return 0;
+              };
             break;
           }
         case XCB_FOCUS_OUT:
-          // TODO(mangalinor) Document code
-          // (what is the difference between XCB_LEAVE_NOTIFY and XCB_FOCUS_OUT)
+          // This happens when desktop is switched or
+          // mouse button is pressed in another window
```
Comment (mmskv) [inline src/dexpo.cpp]: More explicit documentation would fit better
like: "Quit dexpo on lost focus"

Comment (mmskv) [reply src/dexpo.cpp]: No need to tell that XCB_FOCUS_OUT happens when application loses focus. This is straightforward

File: src/config.hpp [hunk 6]
```diff
@@ -17,9 +17,10 @@ const int dexpo_height = 0;
 
 const uint16_t dexpo_padding = 5; ///< Padding around the screenshots
 
-const uint16_t dexpo_hlwidth = 3; ///< Width of the preselected desktop border
-const uint32_t dexpo_hlcolor = 0XFF662C28; ///< Color of the preselection border
-const uint32_t dexpo_bgcolor = 0xAA525252; ///< Background color. TODO Alpha
+const uint16_t dexpo_hlwidth = 4; ///< Width of the preselected desktop border
+const uint32_t dexpo_bgcolor = 0xAA525252; ///< Background color. TODO Alpha and document properly
+const uint32_t dexpo_preselected_desktop_color = 0Xc20a66;///< Color of the preselection border
+const uint32_t dexpo_desktop_color =   0X0066cc;///<Color of the unselected desktops borders
```
Comment (mmskv) [inline src/config.hpp]: Use clang autoformatter god damn

**Review by mmskv — CHANGES_REQUESTED** [review]
Minor changes required

File: src/dexpo.cpp (hunk 1 above)
Comment (TheHussky) [reply src/dexpo.cpp]: Declaring i as size_t would solve both these issues
Noticed that after push, will be solved.

File: src/dexpo.cpp (hunk 2 above)
Comment (TheHussky) [reply src/dexpo.cpp]: fuck

File: src/config.hpp (hunk 6 above)
Comment (TheHussky) [reply src/config.hpp]: I did? God knows wth happened

File: src/dexpo.cpp (hunk 5 above)
Comment (TheHussky) [reply src/dexpo.cpp]: Will fix

File: src/dexpo.cpp (hunk 4 above)
Comment (TheHussky) [reply src/dexpo.cpp]: 1. Adding return 0 or exit(0) to cases of left mouse click and enter press crashes them - the desktop doesn't switch.(Idk why tho, maybe exit happens faster than x server reply or smth like that)
2. (1) is fixed the following way: exit is done in focus out. But choosing the desktop from which dexpo was launched doesn't make focus lost. So it requires special case.

Comment (TheHussky) [reply src/dexpo.cpp]: Do you mean emwh change desktop would fit better in else?

Comment (mmskv) [reply src/dexpo.cpp]: > The desktop doesn't switch.

You need to do `xcb_flush(c)`


> Do you mean emwh change desktop would fit better in else?

Now that i think about it, running ewmh_change_desktop on current desktop won't do anything, so leave it as it is (remove lines 120-122)

**Review by TheHussky — COMMENTED** [review]
lgtm

File: src/config.hpp [hunk 7]
```diff
@@ -20,7 +20,7 @@ const uint16_t dexpo_padding = 5; ///< Padding around the screenshots
 const uint16_t dexpo_hlwidth = 4; ///< Width of the preselected desktop border
 const uint32_t dexpo_bgcolor = 0xAA525252; ///< Background color. TODO Alpha and document properly
 const uint32_t dexpo_preselected_desktop_color = 0Xc20a66;///< Color of the preselection border
-const uint32_t dexpo_desktop_color =   0X0066cc;///<Color of the unselected desktops borders
+const uint32_t dexpo_desktop_color =   0X0066cc;///< Color of the unselected desktops borders
```
Comment (mmskv) [inline src/config.hpp]: Well this is clearly not formatted
too many spaces: ```
... =   0X0066cc...```

No space between code and comment:
```cc;///< Color o...```

Comment (mmskv) [reply src/config.hpp]: I will fix this in the next commit

**Comment by mmskv** [comment]
Border should not obstruct padding.

For example setting `dexpo_border_pres_width` to values greater than `dexpo_padding` should not remove padding

File: src/desktop.cpp [hunk 8]
```diff
@@ -27,15 +27,15 @@ dxp_desktop::dxp_desktop (
   this->pixmap_width = dexpo_width;
   this->pixmap_height = dexpo_height;
 
+  float screen_ratio = float (this->width) / this->height; ///< width/height
```
Comment (TheHussky) [inline src/desktop.cpp:30]: Do you think this comment is even needed?

Comment (mmskv) [reply src/desktop.cpp:30]: In this case not really, as the variable scope is very small.

screen_ratio doesn't convey whether it is width/height or height/width. As the comment is in the doxygen format it can be parsed by Language Server and shown to programmer when he hovers over variable

**Review by mmskv — APPROVED** [review]
